###server-controller with servlet.context-path
GET http://localhost:8081/simple/server/test1

###server-controller without servlet.context-path
GET http://localhost:8081/test1


###client-controller without servlet.context-path - notempty url
GET http://localhost:8082/testClient/test1


###client-controller without servlet.context-path - empty url
GET http://localhost:8082/testClient/root